### ISSUE TITLE
Uploading track fails with 401 Unauthorized but still uploads file

### ISSUE THREAD

**Issue by 50m30n3** [soundcloud/soundcloud-python#68] opened 2016-05-24 20:09 UTC
I've been using this code to upload to soundcloud for the last 5 months without problem.

```
#!/usr/bin/python2 -u
# -*- coding: utf-8 -*-

import sys
reload( sys )
sys.setdefaultencoding( "utf8" )

import soundcloud

soundfile = sys.argv[1]

print( 'Logging into soundcloud...' )

try:
	client = soundcloud.Client(
		client_id='64c56d14d1844681f7cca8c61ec0082a',
		client_secret='3a793d20fd6cf23da7fd66ccc77a57a1',
		username='username',
		password='password',
	)
except Exception, err:
	print( err )
else:
	print( 'OK' )

	print( 'Uploading ' + soundfile )

	trackdata = {
		'title': soundfile,
		'asset_data': open( soundfile , 'rb' ),
	}

	try:
		track = client.post( '/tracks', track=trackdata )
	except Exception, err:
		print( err )
	else:
		print( 'Uploaded!' )
		done = True

```

Since yesterday it fails with the following error:

`401 Client Error: Unauthorized for url: https://api.soundcloud.com/tracks`

The file still gets uploaded successfully though.

This error has also been reported by somebody else [on stackoverflow](http://stackoverflow.com/questions/37421764/python-soundcloud-sdk-upload-track)

**Comment by tomodoherty** [comment] 2016-05-24 20:27
I’m also affected by this issue.

**Comment by gholzmann** [comment] 2016-05-25 06:40
I am seeing the same issue ...

**Comment by different-thinking** [comment] 2016-05-25 19:02
same issue here!

**Comment by cyphase** [comment] 2016-05-26 00:54
This is affecting me as well. The first occurrence for me was just after 2016-05-23 19:00 PDT (2016-05-24 2:00 UTC); whatever happened on SoundCloud's end must have happened within the 24 hours before that.

**Comment by jayrhynas** [comment] 2016-05-26 01:03
I'm having this issue as well. I'm not actually using the python sdk, I have my own swift wrapper that calls the HTTP API for my iOS app. Looking at the [output from curl](git.io/vrPFo), the response has a `Status: 201 Created` header and a `Location` header with the new track URL, but the HTTP response itself has a 401 error code.

**Comment by dieterbethke** [comment] 2016-05-26 10:38
same issue here! Tried to transfer a new podcast show from auphonic to soundcloud. No success, even after retry. :-/

![screenshot 2016-05-26 12 37 31](https://cloud.githubusercontent.com/assets/6697978/15572087/ca56bc4c-233e-11e6-8576-8fd91c21bc41.png)

**Comment by AdamPrimer** [comment] 2016-05-27 05:35
This is not very nice, and hopefully they fix this issue, but for those who want a workaround until then, you can edit `request.py` in this package, changing the last few lines instead to be:

```
    # if redirects are disabled, don't raise for 301 / 302
    if result.status_code in (301, 302):
        if allow_redirects:
            result.raise_for_status()
    elif result.status_code in (401, ):
        if result.headers['Status'] == "201 Created":
            result = requests.get("{}?oauth_token={}".format(
                                  result.headers['Location'], data['oauth_token']))
    else:
        result.raise_for_status()
    return result
```

This will basically check for the 401 + 201 Created case, then request the Location header using the oauth_token, and then return that as the response.

**Comment by gholzmann** [comment] 2016-05-27 16:11
Thanks AdamPrimer for your workaround, I can confirm that it also works here!
I put it in the branch in case somebody else needs it:
https://github.com/gholzmann/soundcloud-python

Still hoping that soundcloud will fix it on their servers ...

**Comment by denis-soundcloud** [comment] 2016-06-17 08:02
Thanks for reporting! This is a duplicate of soundcloud-ruby#51, and is now fixed on our side.

**Closed by denis-soundcloud** 2016-06-17 08:02 UTC

**Comment by jhalfac** [comment] 2019-06-19 06:35
This was a very helpful article for me. I really appreciate it and I have learned alot. I think its interesting even though the upload still goes through. I manage [UpYourPlays.com](https://upyourplays.com/buy-soundcloud-plays/) and I have to say that many artists were complaining about this particular issue. I think it is corrected now thank you.
